apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-barnes
  labels:
    name: parsec-barnes
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:splash2x_barnes
        name: parsec-barnes
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "./run -a run -S splash2x -p barnes -i native -n 4"]
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "12Gi"
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-a-8core"
